update entities to match db schema, update seed data, remove unused code
RealHiring/fullstack-take-home pull request #2
Opened 2021-01-25 15:59 UTC by skruegs

would love your 👀 on the db changes -- i re-ran migrations & no changes, so shouldnt affect the schema itself

2021-01-25 21:09 UTC, sepiette requested changes

2021-01-26 00:49 UTC, skruegs commented on server/src/data/course-sections.js
> +		startDate: '2021-04-13',
there is a date in the past its just not in the diff

2021-01-26 00:54 UTC, skruegs commented on server/src/data/course-sections.js
> +		startDate: '2021-04-13',
(for both of the courses i left one in 2020)

2021-01-26 15:33 UTC, sepiette commented on server/src/data/course-sections.js
> +		startDate: '2021-04-13',
<3

2021-01-26 15:33 UTC, sepiette approved these changes

2021-01-26 15:34 UTC, merged